name = "balance-moim"
compatibility_date = "2024-11-11"

[[d1_databases]]
binding = "DB"
database_name = "balance-moim-db"
database_id = "2549d8d3bab8cbb0e514e6812bca2f8ebcce04327a5b13dc6e63f52fcd550126"
migrations_dir = "drizzle"

